spring:
  application:
    name: gallery-service
  data:
     mongodb:
      uri: mongodb+srv://root:root1234@cluster0-edkji.mongodb.net/gallery?retryWrites=true&w=majority
security:
  oauth2:
    client:
      clientId: "gallery-service"
      clientSecret: "root1234"
      accessTokenUri: http://localhost:9100/uaa/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://localhost:9100/uaa/user/current
server:
  port: 8081
eureka:
  client:
    healthcheck:
      enabled: true

