spring:
  application:
    name: "users"
  data:
    mongodb:
      uri: mongodb+srv://root:root1234@cluster0-edkji.mongodb.net/test?replicaSet=Cluster0-shard-0&readPreference=primary&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-1
eureka:
  client:
    healthcheck:
      enabled: true
server:
  port: 8082