spring:
  application:
    name: "auth-service"
  data:
    mongodb:
      uri: mongodb+srv://root:root1234@cluster0-edkji.mongodb.net/auth_service?replicaSet=Cluster0-shard-0&readPreference=primary&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-1
server:
  servlet:
    context-path: /uaa
  port: 5000
eureka:
  client:
    healthcheck:
      enabled: true