spring:
  data:
    mongodb:
      uri: mongodb+srv://root:root1234@cluster0-edkji.mongodb.net/account?replicaSet=Cluster0-shard-0&readPreference=primary&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-1

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    client:
      clientId: "account-service"
      clientSecret: "root1234"
      accessTokenUri: http://localhost:9100/uaa/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://localhost:9100/uaa/user/current

server:
  servlet:
    context-path: /accounts
  port: 8082