spring:
  profiles:
    active: native
---
spring:
  profiles: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AnanasHiba/neural_networks_netflix_microservices.git
          search-paths:
            - "ms-config-properties/{application}/{profile}"

