spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AnanasHiba/neural_networks_netflix_microservices.git
          search-paths:
            - "ms-config-properties/{application}/{profile}"
  profiles:
    active: git
  application:
    name: config-server
server:
  port: 8888